### ISSUE TITLE
ADAL Libraries for JDK 1.6 with app server

### ISSUE THREAD

**Issue by sathishscjp1** [AzureAD/azure-activedirectory-library-for-java#271] opened 2019-05-22 09:07 UTC
Please share links to find ADAL library which will work in JDK 1.6 
OR 
converting/change the ADAL 1.6.4 library sources into JDK1.6 compatible, will it be advisable? did this for POC and working for login but yet to check for graph APIs.

**Comment by sathishscjp1** [comment] 2019-05-22 11:33
requirement is to use Azure Ad for web application authentication and use graph APIs as well. this for JDK 1.6

**Comment by sangonzal** [comment] 2019-05-22 15:41
@sathishscjp1 ADAL v1.6.4 should work with JDK1.6. out of the box, no changes necessary. If that is not the case, please share the errors that you are running into, and we can try to address those. 

This looks like a duplicate of #269, so closing that one.

**Comment by sathishscjp1** [comment] 2019-05-24 14:30
Hi,
Please find the below error when i am running the application.

[5/24/19 19:09:24:721 IST] 00000027 FfdcProvider W com.ibm.ws.ffdc.impl.FfdcProvider logIncident FFDC1003I: FFDC Incident emitted on D:\Program Files (x86)\IBM\WebSphere\AppServer\profiles\AppSrv01\logs\ffdc\server1_4f125c00_19.05.24_19.09.24.6025902354203323141992.txt com.ibm.ws.webcontainer.filter.WebAppFilterManager.loadFilter 380
[5/24/19 19:09:24:750 IST] 00000027 FfdcProvider W com.ibm.ws.ffdc.impl.FfdcProvider logIncident FFDC1003I: FFDC Incident emitted on D:\Program Files (x86)\IBM\WebSphere\AppServer\profiles\AppSrv01\logs\ffdc\server1_4f125c00_19.05.24_19.09.24.7226372188230210084359.txt com.ibm.ws.webcontainer.filter.WebAppFilterManager.getFilterInstanceWrapper 166
[5/24/19 19:09:24:751 IST] 00000027 webapp E com.ibm.ws.webcontainer.webapp.WebApp logServletError SRVE0293E: [Servlet Error]-[mvc-dispatcher]: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/microsoft/aad/adal4j/AuthenticationException, offset=6
at java.lang.ClassLoader.defineClassImpl(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:264)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:74)
at com.ibm.ws.classloader.CompoundClassLoader._defineClass(CompoundClassLoader.java:830)
at com.ibm.ws.classloader.CompoundClassLoader.localFindClass(CompoundClassLoader.java:745)
at com.ibm.ws.classloader.CompoundClassLoader.loadClass(CompoundClassLoader.java:568)
at java.lang.ClassLoader.loadClass(ClassLoader.java:650)
at java.lang.J9VMInternals.verifyImpl(Native Method)
at java.lang.J9VMInternals.verify(J9VMInternals.java:93)
at java.lang.J9VMInternals.initialize(J9VMInternals.java:170)
at java.lang.Class.forNameImpl(Native Method)
at java.lang.Class.forName(Class.java:213)
at java.beans.Beans.instantiate(Beans.java:189)
at java.beans.Beans.instantiate(Beans.java:80)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager._loadFilter(WebAppFilterManager.java:533)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.loadFilter(WebAppFilterManager.java:475)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.getFilterInstanceWrapper(WebAppFilterManager.java:308)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.getFilterChain(WebAppFilterManager.java:380)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:892)
at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1025)
at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:3763)
at com.ibm.ws.webcontainer.webapp.WebGroup.handleRequest(WebGroup.java:304)
at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:975)
at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1662)
at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:195)
at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:453)
at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:515)
at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:306)
at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:83)
at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1784)
at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:166)
at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217)
at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161)
at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138)
at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204)
at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775)
at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905)
at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1691)

Home Page

java.version ---:1.6.0
java.runtime.name ---:Java(TM) SE Runtime Environment
java.vm.vendor ---:IBM Corporation
java.runtime.version ---:pwa6460_26sr5ifx-20130314_01 (SR5)
java.vendor.url ---:http://www.ibm.com/
user.timezone ---:Asia/Calcutta
user.language ---:en
os.name ---:Windows 8

**Comment by sathishscjp1** [comment] 2019-05-28 09:47
Any further help would be great

**Comment by sangonzal** [comment] 2019-05-28 20:15
@sathishscjp1 Apologies, I was mistaken when I said ADAL should work with Java 6. After discussing with the team here, and checking the [pom history](https://github.com/AzureAD/azure-activedirectory-library-for-java/commit/f99b967990c9a0267589638de7817a28568dc252#diff-600376dffeb79835ede4a0b285078036), the compiler plug-in was updated to target 1.7. I took a look to see if we could move this back to 1.6, but this won't be possible as it would break the library in dozens of places. Language features introduced in Java 7 are used all throughout the code. I think the only to make ADAL work in your scenario would be for you to move to Java 7.

**Comment by sathishscjp1** [comment] 2019-05-31 07:11
Such case, we took source for this below 2 libraries and tweaked somehow the recent JDK feature to make this work with JDK 1.6. Now the "active-directory-java-webapp-openidconnect-master" is working fine for one test azure ad account.  

What is your suggestion to take this forward for application?

1. oauth2-oidc-sdk-5.24.1 
2. adal4j

one minor issue facing is, when connecting through mobile internet in india, no certificate chain issue and it is working fine but when connecting through broadband (think they have some proxy), the login page is working but it is returning below error when acquiring a token. 

[5/31/19 11:14:46:658 IST] 00000022 SystemErr     R Caused by: java.security.cert.CertPathBuilderException: PKIXCertPathBuilderImpl could not build a valid CertPath.; internal cause is: 
	java.security.cert.CertPathValidatorException: The certificate issued by CN=Baltimore CyberTrust Root, OU=CyberTrust, O=Baltimore, C=IE is not trusted; internal cause is: 
	java.security.cert.CertPathValidatorException: Certificate chaining error
[5/31/19 11:14:46:658 IST] 00000022 SystemErr     R 	at com.ibm.security.cert.PKIXCertPathBuilderImpl.engineBuild(PKIXCertPathBuilderImpl.java:411)
[5/31/19 11:14:46:658 IST] 00000022 SystemErr     R 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:258)
[5/31/19 11:14:46:658 IST] 00000022 SystemErr     R 	at com.ibm.jsse2.util.h.b(h.java:81)
[5/31/19 11:14:46:658 IST] 00000022 SystemErr     R 	... 29 more

Thanks
Sathish

**Comment by sathishscjp1** [comment] 2019-06-03 07:58
Please help further suggestion.

**Comment by sangonzal** [comment] 2019-06-05 18:46
@sathishscjp1 The certificate error is related to your websphere configuration, and not adal4j. It seems that you need to download the CN=Baltimore CyberTrust Root and add it to your keystore. A simple online search shows [guidance from IBM](https://www-01.ibm.com/support/docview.wss?uid=swg21369939) on how to diagnose and resolve the exact cert chaining issue that you are running into. 

I'm not sure what you mean by: 

"What is your suggestion to take this forward for application?
1) oauth2-oidc-sdk-5.24.1
2) adal4j"

adal4j brings in oauth2-oidc-sdk as a dependency, so by using adal4j you are indirectly also using oauth2-oidc-sdk.

**Comment by sangonzal** [comment] 2019-06-17 21:34
Closing due to inactivity.

**Closed by sangonzal** 2019-06-17 21:34 UTC
