### ISSUE TITLE
Make library dependencies have an upper version limit. 

### ISSUE THREAD

**Issue by vcolin7** [AzureAD/azure-activedirectory-library-for-java#293] opened 2020-09-10 19:08 UTC
The current POM has a lot of dependencies that use the a versioning format such as this `[1.5,)`:

![image](https://user-images.githubusercontent.com/5799331/92787612-1ac7d280-f35e-11ea-8ee6-3d8872f28a1b.png)

This can cause projects that use these libraries fail since the dependencies can get updated with breaking changes such as what happened on [this issue](https://github.com/Azure/azure-sdk-for-java/issues/14898) in the Azure SDK for Java.

**Comment by joshfree** [comment] 2020-09-10 19:11
Relevant info quoted from @mercer on https://github.com/Azure/azure-sdk-for-java/issues/14898
> 1. the issue for us started appearing on september 6
> 1. same date nimbus-jose-jwt v9.0 is released
> 1. it's either nimbus-jose-jwt, or azure keyvault's api changed on the same date, september 6
> 1. for us, the part of system that failed in the pipeline, is legacy code, no changes to code, or pipeline, or dependencies (declared), or the keyvault  it goes to fetch configuration in more than 6 months
> 1. pipeline runs on code changes from other parts of system (dotnet), and rebuilds all artifacts
> 1. the dependency of your dependency of your dependency (adal4j) is happy to get any future version [6.0.1,)
> 1. this is dangerous for them (nimbusds), for them (adal4j), for you (keyvault client), and for all of us using this
> 1. its a :bomb: waiting to go boom
> 1. it has to be a broken api with nimbus-jose-jwt, they even changed the major version!, while there is not even a patch version change for azure-keyvault-secrets-spring-boot-starter
> 
> Please pin down all your dependency versions, even if I'm wrong about the root cause, as safety for future transient dependency changes.
> 
> (for example all spring starters guarantee that all the jars you get work well together, they do extensive tests to prove this, so that we don't have to)
> 
> Good luck :+1:

**Comment by bganapa** [comment] 2020-09-10 21:41
The issue is being hit thru azurestack combatible azure SDK as well
java.lang.NoSuchMethodError: 'net.minidev.json.JSONObject com.nimbusds.jwt.JWTClaimsSet.toJSONObject()'
..         
         at com.microsoft.aad.adal4j.AuthenticationContext.createClientAuthFromClientAssertion(AuthenticationContext.java:941)              
         at com.microsoft.aad.adal4j.AuthenticationContext.acquireToken(AuthenticationContext.java:241)              
         at com.microsoft.aad.adal4j.AuthenticationContext.acquireToken(AuthenticationContext.java:376)
...         
         at com.microsoft.azure.management.profile_2019_03_01_hybrid.Azure$AuthenticatedImpl.withDefaultSubscription(Azure.java:293)              
         at com.microsoft.azure.management.utility.Authenticate.authenticate(Authenticate.java:141)

**Comment by SomkaPe** [comment] 2020-09-15 03:47
@vcolin7  @joshfree  pom.xml on screenshot is not pom.xml of this project.
pom.xml in this project uses specific versions of dependencies

**Comment by vcolin7** [comment] 2020-09-15 19:48
@SomkaPe I misworded what I meant to say: ADAL4J `1.6.4` has a dependency ([com.nimbusds:oauth2-oidc-sdk:6.5](https://search.maven.org/artifact/com.nimbusds/oauth2-oidc-sdk/6.5/jar)) that has a few dependencies of its own in the format of what is shown in the picture: `[1.5,)`. This causes problems when these transient dependencies introduce breaking changes such as the ones describe in [this issue](https://github.com/Azure/azure-sdk-for-java/issues/14898).

**Comment by SomkaPe** [comment] 2020-09-16 18:25
@vcolin7  Thanks for clarification, I am going to update "com.nimbusds:oauth2-oidc-sdk" dependency to 7.4, that version does not use open-ended version ranges

**Comment by vcolin7** [comment] 2020-09-16 23:56
As an additional note, the folks from Nimbus [mentioned](https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issues/314/make-library-dependencies-have-an-upper#comment-58791157) that all dependencies have closed ranges in 8.x

**Comment by SomkaPe** [comment] 2020-09-17 21:41
@vcolin7  1.6.6 version was released with updated "com.nimbusds:oauth2-oidc-sdk" dependency to 7.4. 
This version is tested and used in msal4j.

**Closed** 2020-09-17 23:55 UTC
