### ISSUE TITLE
build failed with "illegal character: \65279" for AuthenticationContext.java

### ISSUE THREAD

**Issue by omkarksa** [AzureAD/azure-activedirectory-library-for-java#50] opened 2015-08-12 09:59 UTC
Build using mvn on windows fails with error: "illegal character: \65279" for the file /src/main/java/com/microsoft/aad/adal4j/AuthenticationContext.java

Temporary Solution: 
Open the file in Notepad++ and select Encoding -> Convert to UTF-8 without BOM.

Reference: 
http://stackoverflow.com/questions/1726174/how-to-compile-a-java-source-file-which-is-encoded-as-utf-8
http://albert-myptc.blogspot.in/2011/08/illegal-character-65279-when-using-file.html

**Comment by aj-michael** [comment] 2015-08-12 16:32
I did a little digging, and it appears this is a very new issue in this repo.

I ran `git grep $'\xEF\xBB\xBF' $(git rev-list --all)` and found that the change was introduced by this merge commit: https://github.com/AzureAD/azure-activedirectory-library-for-java/commit/057d4d22a0573eae38c992b298a29e06215f391d. Which is strange, because the dev branch that was merged in does not contain the BOM.

At the moment, it is only in the head of the master branch and every commit of the convergence_b2c_preview branch.

**Comment by aj-michael** [comment] 2015-08-12 16:33
Note, this is not a Windows issue. I also fail to build on Linux.

**Comment by kpanwar** [comment] 2015-08-12 16:34
Windows build works fine in eclipse. are you using command line or IDE?

**Comment by aj-michael** [comment] 2015-08-12 16:40
This fails on command line windows and command line linux. Eclipse must just ignore the encoding problem.

**Comment by aj-michael** [comment] 2015-08-12 16:46
You can see the BOM in eclipse by right clicking on AuthenticationContext.java and selecting Properties. Eclipse seems to be doing the "workaround" suggested by Oracle on the bug that they have declared Working as Intended. http://bugs.java.com/view_bug.do?bug_id=4508058

**Closed** 2015-08-12 18:34 UTC

**Comment by omkarksa** [comment] 2015-08-13 02:59
I'm using command line ... 

mvn clean package 

-----Original Message-----
